/**
 * Session Lifecycle Handler
 *
 * Manages session start, message tracking, idle detection, and cleanup.
 * Uses Map<sessionId, SessionState> for in-memory tracking.
 * Logs to ~/.opencode/logs/sessions/{sessionId}.jsonl
 * Persists summaries to ~/.claude/MEMORY/sessions/ on session.idle event.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { fileLog } from "../lib/file-logger.js";
import { StateManager } from "../lib/state-manager.js";

export interface LifecycleSessionState {
	sessionId: string;
	status: "active" | "completed";
	startTime: number;
	lastActivity: number;
	messageCount: number;
	model: string;
	cwd: string;
}

interface SessionStartEntry {
	type: "SESSION_START";
	timestamp: number;
	sessionId: string;
	model: string;
	cwd: string;
}

interface MessageEntry {
	type: "MESSAGE";
	timestamp: number;
	sessionId: string;
	messageCount: number;
}

interface SessionEndEntry {
	type: "SESSION_END";
	timestamp: number;
	sessionId: string;
	durationMs: number;
	messageCount: number;
	model: string;
}

type JsonlEntry = SessionStartEntry | MessageEntry | SessionEndEntry;

const HOME = process.env.HOME || "~";
const SESSION_LOGS_DIR = path.join(HOME, ".opencode", "logs", "sessions");
const MEMORY_SESSIONS_DIR = path.join(HOME, ".claude", "MEMORY", "sessions");

const sessionStates = new Map<string, LifecycleSessionState>();
const stateManager = new StateManager<LifecycleSessionState>(
	path.join(HOME, ".opencode", "pai-state"),
	"lifecycle"
);

function ensureDir(dir: string): void {
	try {
		if (!fs.existsSync(dir)) {
			fs.mkdirSync(dir, { recursive: true });
		}
	} catch (error) {
		fileLog(`Failed to create directory ${dir}: ${error}`, "error");
	}
}

function ensureSessionId(sessionId?: string): string {
	if (sessionId && sessionId.trim() !== "") {
		return sessionId;
	}
	return crypto.randomUUID();
}

function writeJsonlEntry(sessionId: string, entry: JsonlEntry): void {
	try {
		ensureDir(SESSION_LOGS_DIR);
		const logPath = path.join(SESSION_LOGS_DIR, `${sessionId}.jsonl`);
		fs.appendFileSync(logPath, JSON.stringify(entry) + "\n", "utf-8");
	} catch (error) {
		fileLog(`Failed to write JSONL entry for ${sessionId}: ${error}`, "error");
	}
}

function writeSessionSummary(state: LifecycleSessionState): void {
	try {
		ensureDir(MEMORY_SESSIONS_DIR);
		const date = new Date(state.startTime).toISOString().split("T")[0];
		const summaryPath = path.join(MEMORY_SESSIONS_DIR, `${date}-${state.sessionId}.md`);

		const durationSec = Math.round((state.lastActivity - state.startTime) / 1000);
		const content = `# Session Summary

**Session ID:** ${state.sessionId}
**Status:** ${state.status}
**Model:** ${state.model}
**Started:** ${new Date(state.startTime).toISOString()}
**Ended:** ${new Date(state.lastActivity).toISOString()}
**Duration:** ${durationSec} seconds
**Messages:** ${state.messageCount}
**Working Directory:** ${state.cwd}

---
*Generated by PAI-OpenCode Adapter*
`;

		const tempPath = `${summaryPath}.tmp.${process.pid}`;
		fs.writeFileSync(tempPath, content, "utf-8");
		fs.renameSync(tempPath, summaryPath);
		fileLog(`Session summary written to ${summaryPath}`, "info");
	} catch (error) {
		fileLog(`Failed to write session summary: ${error}`, "error");
	}
}

function handleSessionStart(input: { sessionID?: string; model?: { modelID?: string } }): void {
	const sessionId = ensureSessionId(input.sessionID);

	if (sessionStates.has(sessionId)) {
		fileLog(`Session ${sessionId} already tracked, skipping start`, "debug");
		return;
	}

	const now = Date.now();
	const modelId = input.model?.modelID || "unknown";

	const state: LifecycleSessionState = {
		sessionId,
		status: "active",
		startTime: now,
		lastActivity: now,
		messageCount: 0,
		model: modelId,
		cwd: process.cwd(),
	};

	sessionStates.set(sessionId, state);
	stateManager.set(sessionId, state);

	writeJsonlEntry(sessionId, {
		type: "SESSION_START",
		timestamp: now,
		sessionId,
		model: modelId,
		cwd: state.cwd,
	});

	fileLog(`Session started: ${sessionId} (model: ${modelId})`, "info");
}

function handleMessage(input: { sessionID?: string }): void {
	const sessionId = ensureSessionId(input.sessionID);
	let state = sessionStates.get(sessionId);

	if (!state) {
		const persisted = stateManager.get(sessionId);
		if (persisted) {
			state = persisted;
			sessionStates.set(sessionId, state);
		} else {
			fileLog(`Creating new session state for message: ${sessionId}`, "warn");
			state = {
				sessionId,
				status: "active",
				startTime: Date.now(),
				lastActivity: Date.now(),
				messageCount: 0,
				model: "unknown",
				cwd: process.cwd(),
			};
			sessionStates.set(sessionId, state);
		}
	}

	if (state.status === "completed") {
		fileLog(`Message for completed session ${sessionId}, ignoring`, "warn");
		return;
	}

	state.messageCount++;
	state.lastActivity = Date.now();
	stateManager.set(sessionId, state);

	writeJsonlEntry(sessionId, {
		type: "MESSAGE",
		timestamp: state.lastActivity,
		sessionId,
		messageCount: state.messageCount,
	});

	fileLog(`Message tracked for ${sessionId}: count=${state.messageCount}`, "debug");
}

function handleSessionEnd(input: { event: { type: string; properties?: { sessionID?: string } } }): void {
	const sessionId = input.event.properties?.sessionID;

	if (!sessionId) {
		fileLog("Session end event missing sessionId in properties", "warn");
		return;
	}

	let state = sessionStates.get(sessionId);

	if (!state) {
		state = stateManager.get(sessionId);
		if (state) {
			sessionStates.set(sessionId, state);
		}
	}

	if (!state) {
		fileLog(`Session end for unknown session ${sessionId}, skipping`, "warn");
		return;
	}

	if (state.status === "completed") {
		fileLog(`Session ${sessionId} already completed, skipping`, "debug");
		return;
	}

	const now = Date.now();
	const durationMs = now - state.startTime;

	state.status = "completed";
	state.lastActivity = now;
	stateManager.set(sessionId, state);

	writeJsonlEntry(sessionId, {
		type: "SESSION_END",
		timestamp: now,
		sessionId,
		durationMs,
		messageCount: state.messageCount,
		model: state.model,
	});

	writeSessionSummary(state);

	fileLog(
		`Session ended: ${sessionId} (duration: ${Math.round(durationMs / 1000)}s, messages: ${state.messageCount})`,
		"info"
	);
}

/**
 * Direct handlers for pai-unified.ts integration (no event-adapter dependency).
 * These wrap the internal handle* functions for direct invocation from the plugin.
 */

export function onLifecycleSessionStart(sessionId: string, modelId?: string): void {
	try {
		handleSessionStart({ sessionID: sessionId, model: modelId ? { modelID: modelId } : undefined });
	} catch (error) {
		fileLog(`[session-lifecycle] onLifecycleSessionStart error: ${error}`, "error");
	}
}

export function onLifecycleMessage(sessionId: string): void {
	try {
		handleMessage({ sessionID: sessionId });
	} catch (error) {
		fileLog(`[session-lifecycle] onLifecycleMessage error: ${error}`, "error");
	}
}

export function onLifecycleSessionEnd(sessionId: string): void {
	try {
		handleSessionEnd({
			event: {
				type: "session.end",
				properties: { sessionID: sessionId },
			},
		});
	} catch (error) {
		fileLog(`[session-lifecycle] onLifecycleSessionEnd error: ${error}`, "error");
	}
}

export function getSessionState(sessionId: string): LifecycleSessionState | undefined {
	return sessionStates.get(sessionId);
}

export function getAllSessionStates(): Map<string, LifecycleSessionState> {
	return new Map(sessionStates);
}

export function clearAllSessionStates(): void {
	sessionStates.clear();
}

export function getSessionLogsDir(): string {
	return SESSION_LOGS_DIR;
}

export function getMemorySessionsDir(): string {
	return MEMORY_SESSIONS_DIR;
}
